In [1]:
import pandas as pd

In [3]:
f = pd.read_excel('data/restitution-41-20250418172522 jeux BI Ida.xls')
f

,Filtres sélectionnées,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Type d'activité,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Type entité,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Type partie prenante,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Périmètre consolidation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Contrôle,Exercice 2024-2025,Exercice 2024-2025,NaN,NaN,NaN,NaN,NaN
5,Exercice reporting,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Période de collecte,Non,Non,NaN,NaN,NaN,NaN,NaN
7,Confidentialité,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Secteur,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Entité,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Entités concernées,Date génération\nrestitution,NaN,NaN,NaN,NaN,NaN,NaN
15,US_Entité 1,18/04/2025,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Liste des données qui seront utilisées pour vo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Code exercice de reporting,Code questionnaire,Type d'activité,Type d'entité,Entité,Type de PP,Périmètre consolidation,Période de collecte
21,04_2024-03_2025,REA_ENV_US_PP.INT,Générique,Usine,Entité 1,Client Interne,Consolidation,T3
22,04_2024-03_2025,REA_ENV_US_PP.INT,Générique,Usine,Entité 1,Client Interne,Consolidation,T4
23,04_2024-03_2025,REA_GO_SI_PP.INT,Générique,Usine,Entité 1,Client Interne,Consolidation,A1

In [7]:
df_onglet_2 = pd.read_excel('data/restitution-41-20250418172522 jeux BI Ida.xls', sheet_name="Restit Brute (Total Répdts)", engine="calamine")

In [8]:
df_onglet_2

,Unnamed: 0,Code NORME,Nom NORME,Source,Code Axe\nRAPPORT,Nom axe\nRAPPORT,Code axe\nAPP,Nom axe\nAPP,Code thématique\nRAPPORT,Nom thématique\nRAPPORT,...,Total\nMontant\nCollecte\nRéelle\nExercice N-1\nC15-V01,Total\nValo. Financière\nCollecte\nRéelle\nExercice N-1\nC15-V01,Total\nMontant\nCollecte\nRéelle\nExercice N\nC15-V01,Total\nValo. Financière\nCollecte\nRéelle\nExercice N\nC15-V01,Total\nMontant\nCollecte\nO.Strat Plafond\nExercice N\nC15-V01,Total\nMontant\nCollecte\nO.Strat Plancher\nExercice N\nC15-V01,Total\nValo. Financière\nCollecte\nO.Strat\nExercice N\nC15-V01,Total\nMontant\nCollecte\nO.Opér. Plafond\nExercice N\nC15-V01,Total\nMontant\nCollecte\nO.Opér. Plancher\nExercice N\nC15-V01,Total\nValo. Financière\nCollecte O.Opér.\nExercice N\nC15-V01
0,NaN,ESRS,ESRS directive CSRD,Xtrafi,E,Environnement,EN,Environnement,E3,Ressources en eau et marines,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Xtrafi,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,510000.0,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,Xtrafi,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_onglet_2.columns

Index(['Unnamed: 0', 'Code NORME', 'Nom NORME', 'Source', 'Code Axe\nRAPPORT',
       'Nom axe\nRAPPORT', 'Code axe\nAPP', 'Nom axe\nAPP',
       'Code thématique\nRAPPORT', 'Nom thématique\nRAPPORT',
       'Code thématique\nAPP', 'Nom thématique\nAPP', 'Code Ind.N1\nRAPPORT',
       'Nom Ind.N1\nRAPPORT', 'Code Ind.N1\nAPP', 'Nom Ind.N1\nAPP',
       'Type de\ncompilation\nINDICATEUR\n(C = Cumul,\nM = Moyenne)',
       'Type de\ndonnées\nINDICATEUR\n(Q = quantitatif,\nK = qualitatif,\nA = action)',
       'Code Ind.N2\nRAPPORT', 'Nom Ind.N2\nRAPPORT', 'Code Ind.N2\nAPP',
       'Nom Ind.N2\nAPP', 'Code Ind.N3\nRAPPORT', 'Nom Ind.N3\nRAPPORT',
       'Code Ind.N3\nAPP', 'Nom Ind.N3\nAPP', 'Code question\nRAPPORT',
       'Nom question\nRAPPORT', 'Code question\nAPP', 'Nom Question\nAPP',
       '% pondération\nsecteur', 'Unité de\nsaisie', 'Unité\nconversion',
       'Monnaie\nlocale', 'Unité\nValorisation\nfinancière',
       'Total\nMontant\nCollecte\nRéelle\nExercice N-1',
       'Total\nValo. Financière\nCollecte Réelle\nExercice N-1',
       'Total\nMontant\nCollecte\nRéelle\nExercice N',
       'Total\nValo. Financière\nCollecte Réelle\nExercice N',
       'Total\nMontant\nCollecte\nO.Strat Plafond\nExercice N',
       'Total\nMontant\nCollecte\nO.Strat Plancher\nExercice N',
       'Total\nValo. Financière\nCollecte\nO.Strat\nExercice N',
       'Total\nMontant\nCollecte\nO.Opér.Plafond\nExercice N',
       'Total\nMontant\nCollecte\nO.Opér.Plancher\nExercice N',
       'Total\nValo. Financière\nCollecte\nO.Opér.\nExercice N',
       'Total\nMontant\nCollecte\nRéelle\nExercice N-1\nC15-V01',
       'Total\nValo. Financière\nCollecte\nRéelle\nExercice N-1\nC15-V01',
       'Total\nMontant\nCollecte\nRéelle\nExercice N\nC15-V01',
       'Total\nValo. Financière\nCollecte\nRéelle\nExercice N\nC15-V01',
       'Total\nMontant\nCollecte\nO.Strat Plafond\nExercice N\nC15-V01',
       'Total\nMontant\nCollecte\nO.Strat Plancher\nExercice N\nC15-V01',
       'Total\nValo. Financière\nCollecte\nO.Strat\nExercice N\nC15-V01',
       'Total\nMontant\nCollecte\nO.Opér. Plafond\nExercice N\nC15-V01',
       'Total\nMontant\nCollecte\nO.Opér. Plancher\nExercice N\nC15-V01',
       'Total\nValo. Financière\nCollecte O.Opér.\nExercice N\nC15-V01'],
      dtype='object')

: