In [1]:
import pandas as pd

In [19]:
df = pd.read_excel("./data/restitution-30-20250312161809.xls",header=None,engine= "calamine")

df

,0,1,2,3,4,5,6,7
0,Filtres sélectionnées,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Type d'activité,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Type entité,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Type partie prenante,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Périmètre consolidation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Contrôle,2025 CIVIL,NaN,NaN,NaN,NaN,NaN,NaN
6,Exercice reporting,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Période de collecte,Non,NaN,NaN,NaN,NaN,NaN,NaN
8,Confidentialité,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Secteur,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Entité,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Entités concernées,Date génération\nrestitution,NaN,NaN,NaN,NaN,NaN,NaN
16,PME50_CLIENT 001,12/03/2025,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Liste des données qui seront utilisées pour vo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Code exercice de reporting,Code questionnaire,Type d'activité,Type d'entité,Entité,Type de PP,Périmètre consolidation,Période de collecte
22,C2025,Q_CLT001_GOV,TAXO03_Industrie manufacturière,pme < 50 salariés,CLIENT 001,Fournisseur Externe,Hors consolidation,A1
23,C2025,Q_CLT001_ENV,TAXO03_Industrie manufacturière,pme < 50 salariés,CLIENT 001,Fournisseur Externe,Hors consolidation,S1

In [23]:
def load_excel_data_dynamic_start(file_path):
    # Lire le fichier sans parser les colonnes pour chercher la ligne clé
    preview_df = pd.read_excel(file_path,header=None, engine= "calamine")

    # Chercher la ligne contenant le texte cible
    start_row_idx = preview_df[0].astype(str).str.contains("Liste des données qui seront utilisées pour", case=False, na=False)

    if start_row_idx.any():
        # Trouver l'index de la ligne et +1 pour commencer après
        start_index = start_row_idx[start_row_idx].index[0] + 1
        df = pd.read_excel(file_path, skiprows=start_index, engine="calamine")
        return df
    else:
        raise ValueError("❌ Ligne de début de données introuvable dans le fichier.")

In [25]:
file_path = "./data/restitution-30-20250312161809.xls"
df_onglet_1 = load_excel_data_dynamic_start(file_path)
df_onglet_1

,Code exercice de reporting,Code questionnaire,Type d'activité,Type d'entité,Entité,Type de PP,Périmètre consolidation,Période de collecte
0,C2025,Q_CLT001_GOV,TAXO03_Industrie manufacturière,pme < 50 salariés,CLIENT 001,Fournisseur Externe,Hors consolidation,A1
1,C2025,Q_CLT001_ENV,TAXO03_Industrie manufacturière,pme < 50 salariés,CLIENT 001,Fournisseur Externe,Hors consolidation,S1